### ISSUE TITLE
My design is not loading!

### ISSUE THREAD

**Issue by SharifTanvir** [KlausSchaefers/qux-low-code-example#1]
this is my code: 

`<template>
  <div class="home debug">
    <QUX :app="app" :config="config" :showDebug="true" v-model="payload"/>
  </div>
</template>
<style lang="scss">
.home {
  height: 100%;
}
</style>

<script>

import Vue from "vue";
import QUX from 'qux-lowcode'
Vue.use(QUX);

import app from '../qux/app.json'

export default {
  name: 'home',
  data: function () {
    return {
      app: app,
      hash: "a2aa10aJRJKtwAVFzyvmaR709lFEeq84JJhVrjMDTXYiZbKZFb8vujOIPuRu",
      payload: {
        name: 'Md Shariful',
        lastname: 'Islam Tanvir'
      },
      config: {
        debug: {
          resize: false,
          logLevel: 2
        },
        css: {
          grid: true,
          justifyContentInWrapper: true
        },
        router: {
          key: 'screenName',
          prefix: 'example1'
        }
      },
      showPayload: false
    }
  },
  components: {
  },
  methods: {
    uploadImage (value, element, e) {
      console.debug('Home.methodA()', JSON.stringify(value), element, e)
    }
  }
}
</script>
`

API hit correctly and i get my design correctly in app.json but i can not see my design in browser.

**Comment by KlausSchaefers** [comment]
what is the error?

**Comment by KlausSchaefers** [comment]
Try this one: https://github.com/KlausSchaefers/vue-low-code-example. This is newer
